---
title: "DHS facility survey"
author: "Rushad Faridi, PhD"
---


```{r setup, echo=FALSE}
library(tidyverse)
library(knitr)
library(summarytools)
library(kableExtra)
library(labelled)
opts_chunk$set(comment=NA, warning=FALSE, echo=FALSE, message=FALSE, results="asis", cache=FALSE, prompt=FALSE)
fac17 <- readRDS("./rdata/fac17.rds")
```

```{r}
fac17_small <- fac17 %>% 
                 select(-contains("_"))  %>% 
		 unlabelled()
```




```{r, eval=F, echo=F}
fac17_label <- fac17_small %>% 
                       lapply(attr, which="label") %>% 
		       lapply(function(x) ifelse(is.null(x), "", x)) %>% 
		       unlist() %>% 
		       tibble::enframe()  %>% 
		       rename(var_name=name, 
			      var_label=value)


```



```{r, echo=F, eval=F }
kable(fac17_label, format="html")  %>% 
      kable_styling(full_width=TRUE) 
```


# Data description

```{r}
dfSummary(fac17_small,
	  labels.col = TRUE,
	  plain.ascii = FALSE, 
	  style= "grid",
	  valid.col=FALSE,
	  na.col=FALSE,
	  max.distinct.values=6,
	  graph.col=F)
```



# Descriptive statistics 

```{r, eval=F}
descr(fac17, style="rmarkdown")
``




